# Generated by Django 5.1.4 on 2024-12-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('duration', models.DurationField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('original_video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
