# Generated by Django 5.1.4 on 2024-12-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('anthropic_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('max_video_height', models.IntegerField(choices=[(240, '240p'), (360, '360p'), (480, '480p'), (720, '720p'), (1080, '1080p')], default=720)),
                ('use_he_aac_v2', models.BooleanField(default=True)),
            ],
        ),
    ]
