# Generated by Django 5.1.4 on 2024-12-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='audio',
            field=models.FileField(null=True, upload_to='audios/'),
        ),
    ]
