# Generated by Django 5.1.4 on 2024-12-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_youtubevideo_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'verbose_name': 'YouTube Video', 'verbose_name_plural': 'YouTube Videos'},
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='audio',
            field=models.FileField(upload_to='audios/'),
        ),
    ]
