# Generated by Django 5.1.4 on 2024-12-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='language',
            field=models.CharField(max_length=32),
        ),
    ]
