# Generated by Django 5.1.4 on 2024-12-29 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_subtitle_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtitle',
            unique_together=set(),
        ),
    ]
