[project]
name = "wandlung"
version = "0.1.0"
description = "Wandlung REST api server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.4",
    "django-ninja>=1.3.0",
]
